/*
 *
 * MapPage constants
 *
 */

enum ActionTypes {
  DEFAULT_ACTION = 'app/MapPage/DEFAULT_ACTION',
  LOAD_TRAVEL_MAPS = 'app/MapPage/LOAD_TRAVEL_MAPS',
  LOAD_TRAVEL_MAPS_SUCCESS = 'app/MapPage/LOAD_TRAVEL_MAPS_SUCCESS',
  LOAD_TRAVEL_MAPS_ERROR = 'app/MapPage/LOAD_TRAVEL_MAPS_ERROR',

  LOAD_POST_READ_MORE = 'app/MapPage/LOAD_POST_READ_MORE',
  LOAD_POST_READ_MORE_SUCCESS = 'app/MapPage/LOAD_POST_READ_MORE_SUCCESS',
  LOAD_POST_READ_MORE_ERROR = 'app/MapPage/LOAD_POST_READ_MORE_ERROR',
}

export default ActionTypes;
